name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtualenv
        run: python -m virtualenv .venv

      - name: Install dependencies
        shell: bash
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        shell: bash
        run: |
          source .venv/bin/activate
          pip install flake8
          flake8 .
